#include "pelion_log.h"
#include "pelion_thread.h"
#include "pelion_time.h"
#include "pelion_stdlib.h"
#include "pelion_system.h"

#include "app.h"
#include "traffic_queue.h"

#include <stdio.h>


/**
 * @file main.c
 */
struct Pelion_Globals pelion_globals = {0};

struct Traffic_Queue Q1 = {.id = "Q1"};
struct Traffic_Queue Q2 = {.id = "Q2"};

void* request_generator_infinite_loop(void *arg);
void* token_generator_infinite_loop(void *arg);
void* request_servicer_infinite_loop_no_busy_waiting(void *arg);

struct Arg_Type arg_types_defs[] = {
    {
        'r', "request-generation-interval (in seconds) by T1",
        &(pelion_globals.r_request_generation_interval_T1)
    },
    {
        'R', "tokens required by each request",
        &(pelion_globals.R_tokens_per_request)
    },
    {
        'L', "maximum unused tokens at a time (generated by T2)",
        &(pelion_globals.L_max_unused_tokens)
    },
    {
        'x', "token-generation interval (in seconds) by T2",
        &(pelion_globals.x_token_generation_interval_T2),
    },
    {
        't', "time required for processing of each request by S",
        &(pelion_globals.t_time_per_request_S)
    },
    {
        'd', "delimiter",
        NULL
    }
};

struct Arg_Type *arg_types = (struct Arg_Type *) arg_types_defs;

/**
 * Entry-Point function of main-thread.
 */
int main(int argc, char *argv[]) {

    /*
     * Initialize the mutexes and condition-variables used in the system.
     */
    pelion_init_mutex(&log_mtx);
    pelion_init_mutex(&(Q1.mtx));
    pelion_init_mutex(&(Q2.mtx));

    pelion_init_condition_variable(&(Q2.cond));


    /*
     * Initialize the backend logger.
     */
    pelion_init_log_on_device();


    /*
     * Do other device-specific initializations.
     */
    pelion_device_specific_init();


    /*
     * Get the log-level at startup.
     */
    current_log_level = pelion_get_current_log_level();


    /*
     * Fetch the configurable parameters passed via command line.
     */
    parse_cmd_line_args(argc, argv);


    /*
     * Error out if R_tokens_per_request is greater than
     * L_max_unused_tokens.
     */
    if(pelion_globals.R_tokens_per_request >
       pelion_globals.L_max_unused_tokens) {

        pelion_log(ERROR, "R cannot be larger than L, exiting ..\n");
        pelion_exit();
    }


    pelion_log(EVENT, "emulation begin\n");

    /*
     * Start the threads.
     */
    pelion_start_thread(request_generator_infinite_loop, NULL);
    pelion_start_thread(token_generator_infinite_loop, NULL);
    pelion_start_thread(request_servicer_infinite_loop_no_busy_waiting, NULL);


    while(1) {

        current_log_level = pelion_get_current_log_level();

        pelion_log(DEBUG, "DEBUG dummy log\n");
        pelion_log(INFO,  "INFO dummy log\n");
        pelion_log(WARN,  "WARN dummy log\n");

        pelion_delay_us(1000000UL);
    }

    return 0;
}
