#include "pelion_log.h"
#include "pelion_mutex.h"
#include "pelion_thread.h"
#include "pelion_time.h"
#include "pelion_stdlib.h"

#include "app.h"
#include "traffic_queue.h"

struct Pelion_Globals pelion_globals = {0};

struct Traffic_Queue Q1;
struct Traffic_Queue Q2;

void* request_generator_infinite_loop(void *arg);
void* token_generator_infinite_loop(void *arg);

struct Arg_Type arg_types_defs[] = {
    {
        'r', "request-rate of T1",
        &(pelion_globals.r_request_rate_T1)
    },
    {
        'R', "tokens required by each request",
        &(pelion_globals.R_tokens_per_request)
    },
    {
        'L', "maximum unused tokens at a time (generated by T2)",
        &(pelion_globals.L_max_unused_tokens)
    },
    {
        'x', "token-rate of T2",
        &(pelion_globals.x_tokens_rate_T2),
    },
    {
        't', "time required for processing of each request by T3",
        &(pelion_globals.t_time_per_request_T3)
    },
    {
        'd', "delimiter",
        NULL
    }
};

struct Arg_Type *arg_types = (struct Arg_Type *) arg_types_defs;


int main(int argc, char *argv[]) {

    /*
     * Initialize the mutexes used in the system.
     */
    pelion_init_mutex(&log_mtx);
    pelion_init_mutex(&(Q1.mtx));
    pelion_init_mutex(&(Q2.mtx));

    /*
     * Initialize the backend logger.
     */
    init_log_on_device();

    /*
     * Fetch the configurable parameters passed via command line.
     */
    parse_cmd_line_args(argc, argv);

    /*
     * Start the threads.
     */
    start_thread(request_generator_infinite_loop, NULL);
    start_thread(token_generator_infinite_loop, NULL);

    while(1) {
        pelion_delay_ms(1000);
    }

    return 0;
}
