#include "pelion_log.h"
#include "pelion_thread.h"
#include "pelion_time.h"
#include "pelion_stdlib.h"

#include "app.h"
#include "traffic_queue.h"

/**
 * @file main.c
 */
struct Pelion_Globals pelion_globals = {0};

struct Traffic_Queue Q1;
struct Traffic_Queue Q2;

void* request_generator_infinite_loop(void *arg);
void* token_generator_infinite_loop(void *arg);
void* request_servicer_infinite_loop_no_busy_waiting(void *arg);


struct Arg_Type arg_types_defs[] = {
    {
        'r', "request-rate of T1",
        &(pelion_globals.r_request_rate_T1)
    },
    {
        'R', "tokens required by each request",
        &(pelion_globals.R_tokens_per_request)
    },
    {
        'L', "maximum unused tokens at a time (generated by T2)",
        &(pelion_globals.L_max_unused_tokens)
    },
    {
        'x', "token-rate of T2",
        &(pelion_globals.x_tokens_rate_T2),
    },
    {
        't', "time required for processing of each request by T3",
        &(pelion_globals.t_time_per_request_T3)
    },
    {
        'd', "delimiter",
        NULL
    }
};

struct Arg_Type *arg_types = (struct Arg_Type *) arg_types_defs;


int main(int argc, char *argv[]) {

    /*
     * Initialize the mutexes and condition-variables used in the system.
     */
    pelion_init_mutex(&log_mtx);
    pelion_init_mutex(&(Q1.mtx));
    pelion_init_mutex(&(Q2.mtx));

    pelion_init_condition_variable(&(Q2.cond));


    /*
     * Initialize the backend logger.
     */
    init_log_on_device();


    /*
     * Fetch the configurable parameters passed via command line.
     */
    parse_cmd_line_args(argc, argv);


    /*
     * Start the threads.
     */
    pelion_start_thread(request_generator_infinite_loop, NULL);
    pelion_start_thread(token_generator_infinite_loop, NULL);
    pelion_start_thread(request_servicer_infinite_loop_no_busy_waiting, NULL);


    while(1) {

        current_log_level = pelion_get_current_log_level();

        pelion_log(DEBUG, "DEBUG dummy log\n");
        pelion_log(INFO,  "INFO dummy log\n");
        pelion_log(WARN,  "WARN dummy log\n");

        pelion_delay_us(1000000U);
    }

    return 0;
}
