#include "device_defines.h"

#include "pelion_cmd_args.h"
#include "pelion_system.h"
#include "pelion_log.h"

#include <stdlib.h>
#include <string.h>

struct Pelion_Globals pelion_globals = {0};

struct Arg_Type arg_types[] = {
    {
        'r', "request-rate of T1",
        &(pelion_globals.r_request_rate_T1)
    },
    {
        'R', "tokens required by each request",
        &(pelion_globals.R_tokens_per_request)
    },
    {
        'L', "maximum unused tokens at a time (generated by T2)",
        &(pelion_globals.L_max_unused_tokens)
    },
    {
        'x', "token-rate of T2",
        &(pelion_globals.x_tokens_rate_T2),
    },
    {
        't', "time required for processing of each request by T3",
        &(pelion_globals.t_time_per_request_T3)
    },
    {
        'd', "delimitor",
        NULL
    }
};


void parse_cmd_line_args(int argc, char *argv[]) {

    int i = 0, j = 0;

    for(i = 0; i < argc; i++) {

        if(argv[i][0] == '-') {

            j = 0;
            while(1) {

                if(arg_types[j].value == NULL) {
                    break;

                } else {
                    if( (strlen(argv[i]) == 2) &&
                        (argv[i][1]) == arg_types[j].id) {
                        *(arg_types[j].value) = atoi(argv[i + 1]);

                        pelion_log(DEBUG, "[-%c] [%s] ==> [%d]\n",
                                  arg_types[j].id,
                                  arg_types[j].user_friendly_name,
                                  *(arg_types[j].value));

                        break;
                    }
                }

                j++;
            }
        }
    }

    /*
     * Now check whether any field could not be filled up.
     */
    j = 0;
    while(1) {
        if(arg_types[j].value == NULL) {
            break;

        } else {
            if(*(arg_types[j].value) <= 0)
            {
                pelion_log(ERROR, "Invalid/Unknown value for [-%c] [%s], "
                          "exiting\n",
                          arg_types[j].id,
                          arg_types[j].user_friendly_name);

                pelion_exit();
            }
        }

        j++;
    }
}




